title:            Laurence
tagline:          
description:      '自由、睿智'
url:              laurenceqi.github.io
baseurl:          http://laurenceqi.github.io/

paginate:         5

# Custom vars
version:          2.1.0

plugins: [jekyll-paginate]