title:            Laurence
tagline:          
description:      '读书、思考'
url:              laurenceqi.me
baseurl:          /


paginate:         5

# Custom vars
version:          2.1.0

plugins: [jekyll-paginate]